remote_theme: pages-themes/time-machine@v0.2.0

plugins:
  - jekyll-remote-theme # add this line to the plugins list if you already have one

title: "Rutika Mahagaokar"
description: "Results-driven professional with 7+ years’ experience in business analysis, systems implementation and project coordination across banking and IT domains"
